export enum ERROR_CODE{
    DEFAULT = 400,
    UNAUTHORISE = 401,
    FAILED = 0,
    EXCEPTION = 2, 
    INVALIDREQUEST = 3,   
    CONTESTNOTFOUND = 4,
    INSUFFICIENTBALANCE = 501,
    CLIENT_OUTDATED = 5,
    RESYNC = 6,
    RETRY = 7,
    GAME_ENDED = 8,
    NO_OPPONENT_FOUND = 9
}